name: "Bump Version"
on:
  push:
    branches:
      - "main"
jobs:
  bump-version:
    name: "Bump Version on master"
    runs-on: ubuntu-latest
    steps:
      - name: Conventional Commits Version Bump
        uses: soamee/gh-action-conventional-commits@v8.0.3
        with:
          # Prefix that is used for the git tag
          tag-prefix: "VERSION BUMP"
